### ISSUE TITLE
badges and ci testing

### ISSUE THREAD

**Issue by musm** [JuliaMath/Sleef.jl#1]
cc: @ararslan  I think you're the expert here, but  I can't figure out appveyor and how to get the codecov and coveralls to sync up

**Comment by ararslan** [comment]
AppVeyor is kind of weird in that it runs on a user's account rather than an account associated with an organization. To set this repo up under your account, you can go to https://www.appveyor.com, click "sign in" in the top right if you have an account, or "sign up for free" in the center if you don't have one. Once you're logged in, you should end up at https://ci.appveyor.com/projects. Then select New Project and scroll down to Sleef.jl. You can keep all of the default settings, but I like to check "skip branches without appveyor.yml" in the General tab. You can get the Markdown snippet for the CI status badge from the Badges tab.

Let me know if you run into any more issues!

**Comment by ararslan** [comment]
Actually, looks like Simon already set up AV under his account here, so you can ignore the above for this repo.

**Comment by musm** [comment]
Looks like access is denied for appveyor, perhaps it erased history when I moved over the repo? I think the rest are now working, just waiting on the build to verify.

**Comment by ararslan** [comment]
The coverage badges can sometimes take about a day to show something other than "unknown" on the readme.

**Comment by ararslan** [comment]
Oh wait, did this used to be Libm.jl?

**Comment by musm** [comment]
Yes this is the feature complete port of Sleef.jl see the readme

**Comment by musm** [comment]
See: https://github.com/JuliaMath/Libm.jl/issues/54

**Comment by ararslan** [comment]
Oh, I meant was Libm.jl renamed to Sleef.jl but that is apparently not the case. Disregard.

**Comment by musm** [comment]
Great

**Comment by musm** [comment]
Everything save Appveyor is now working. It looks like it's still cached to simons account, but I get Project not found or access denied.

**Comment by ararslan** [comment]
Oh, I see, it looks like it isn't actually set up under Simon's account. So if you follow the steps I laid out in https://github.com/JuliaMath/Sleef.jl/issues/1#issuecomment-251862245, you should be good to go. Then you can just replace the AppVeyor badge that's currently in the README with the one you get once you set it up on your account.

**Comment by musm** [comment]
Got it thanks! forgot to update the readme....

**Comment by ararslan** [comment]
Fantastic!
